# Generated by Django 2.2 on 2021-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransactiontbl',
            name='purchase_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
