# Generated by Django 2.2 on 2021-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210127_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstbl',
            name='product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
